### PR TITLE
Object orient

### PR DESCRIPTION
**Pull request by KennethNielsen**
Hallo socos devs

This is my attempt to object orient socos. Obviously, object oriented is not a goal in itself, but since the usual definition of when to object orient (i.e. you have a bunch of functions that share state) seems to apply here, I thought it was a good idea. It also gets rid of global variables and other such annoying stuff.

A few things to note about the implementation:
 1. There no longer exists such a thing as the dict of commands, it is formed at run-time in two steps. First, when the class is formed, commands specifications are added to a command_list either by decorating methods in the SoCos class e.g:

 ```python
     @add_command(requires_ip=False)
     def partymode(self):
         """Put all the speakers in the same group, a.k.a Party Mode."""
         self.current_speaker.partymode()
 ```

 or by adding command specs to the command_list directly, e.g (line 488):

 ```python
    # Add music service commands
    for method_name in ['index', 'tracks', 'albums', 'artists', 'playlists',
                         'sonos_playlists']:
        command_list.append(
            CommandSpec(requires_ip=True, command_name='ml_' + method_name,
                        obj_name='music_lib', method_name=method_name)
        )
 ```

 Then when the SoCos object is initialised the OrderedDict ``self.commands`` is populated with actual methods. It is not as simple an implementation as keeping a list (with the decorator and all), but it gets rid of the need to manually keep a command list in sync and it is much more flexibly.

 2. In the implementation described in (1), the order in which the commands appear in help (which is maintained), is determined by the order in which methods are defined or command specs added in the class.

 3. I removed the special case where-in you could specify a command by just a string if it was named the same as the corresponding method in soco. It was only every used for one command anyway, so I didn't think it was worth keeping the special case handling. Most of this special case code was in ``_call_func`` which is therefore remove.

 4. I moved the application of the ``requires_coordinator`` decorator into the ``add_command`` decorator. This could be done conveniently by simply passing an extra argument into ``add_command`` and so it fits nicely in there. It also keeps the list of decorators from getting too long.

 5. I also fixed a bug (around 150), wherein, if you called a command that needs an IP without one, you will not only get the custom error message printed out in ``_check_args`` but also an error from an exception when you try to call None with *None. So now, if ``_check_args`` returns None, None, which is the indication of a missing IP, just return immediately.

Please test and let me know what you think.

Regards Kenneth

### CODE REVIEW

**Comment by stefankoegl** [comment]
Great work! From my point of view this could go in whenever you're ready.

**Comment by stefankoegl** [comment]
I just noticed that the build for this PR failed (https://travis-ci.org/SoCo/socos/builds/62547424). Those are just minor issues, but they should probably be fixed before the merge, so that we have a clean state.

**Comment by KennethNielsen** [comment]
Hi @stefankoegl.

Thanks for looking it over. I actually wasn't even aware that we used travis for socos, because it doesn't have the little red or green icons next to the commits. Do you know who set that up for SoCo?

In any case, after much fighting with different pylint versions it now passes on everything else than python 3.2 and that looks like an error in the travis and pylint system. I remeber that we at some point had problems with 3.2 in SoCo as well, but I can see that it is re-enabled, so at least that original problem does not exist anymore. I wonder what this is.

**Comment by stefankoegl** [comment]
I did set up the integration for SoCo. I've just double-checked socos' integration, and found some wrong config which I've now fixed (hopefully).

I think the build problem you're seeing now has been fixed in SoCo/Soco#257

**Comment by KennethNielsen** [comment]
@stefankoegl Ok, so there was a problem with the setup, but it has now been fixed at least for SoCo but what about SoCos, it is something that requires a projects specific fix? In any case I just re-startet the build at it still fails for 3.2.

**Comment by stefankoegl** [comment]
Yes, I meant that the same fix (pinning the dependency to the same version) should also work for socos.

**Comment by KennethNielsen** [comment]
After some fighting with the setup, it should now pass.

I think I will suggest dropping 3.2 since it is a lot of tools that needs to be pinned and since socos is an application more than a lib I think we can allow ourselves to be a little more restrictive. But that will be a topic for another thread.

Ok to merge in this form?

**Comment by stefankoegl** [comment]
Yes, definitely!

**Pull request merged**
