### PR TITLE
Fix minor typo in help example

### PR DESCRIPTION
**Pull request by walshie4**

### CODE REVIEW

**Comment by kberg** [comment]
Why closed? Was it wrong?

**Comment by walshie4** [comment]
No it's just been open for long enough that I gave up on it getting merged.

**Comment by KennethNielsen** [comment]
Hi @walshie4 

Sorry about the delayed response time. I'm unsure, but I think we may have changed the code so much now, that it is no longer relevant, but it should be checked. Please just leave it open, we move slowly, but we do move.

Regards Kenneth

**Comment by walshie4** [comment]
This is no longer relevant, comment is now removed

**Pull request closed without merging**
