### PR TITLE
Get or set player_name.

### PR DESCRIPTION
**Pull request by petteraas**
Requires https://github.com/SoCo/SoCo/pull/185 so I guess we can leave this untill first socos release that connects with SoCo 0.9 ( or something like that )

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Hi @petteraas 

I'm afraid I broke the possibility to automatically merge this, with the object orient PR. Let me know if you need any help with the new way of registering a command.

Regards Kenneth

**Comment by petteraas** [comment]
@KennethNielsen I had apparently forgotten about this.

I had a look at it now, and I got a unexpected problem, the accessor/mutator for player_name seems to have been added in SoCo 0.9, but when I test the current version of socos with SoCo 0.9 I get a problem with sonos.group.coordinator 'randomly' set to None even though I know I'm in 'partymode', this causes e.g. 'state()' to break, if you happen to know why, that would be nice, but if not I'll take another look! 

The new registering of commands looks nice, I think I saw right away how to do it!

Btw, perhaps we should update all the way to latest SoCo? , it can be done as a separate PR though!

**Comment by petteraas** [comment]
updated this after release of #55

**Comment by KennethNielsen** [comment]
+1

**Comment by stefankoegl** [comment]
Closing in favor of #76.

**Pull request closed without merging**
