### PR TITLE
Update Python to 3.7

### PR DESCRIPTION
**Pull request by stefankoegl**
This pull request updates the supported (and tested) Python versions up to 3.7. For the more recent python versions I also had to update the development requirements, which in turn required some cosmetic changes to make pylint and flake8 happy.

### CODE REVIEW

**Comment by polyzen** [comment]
3.7 is availabe, you just have to use the snippet:

```
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
```

**Comment by stefankoegl** [comment]
@polyzen thanks! Is that the "official" way to do it, or a workaround?

**Comment by polyzen** [comment]
Seems to be the official way to do it until the distros are updated.

**Comment by KennethNielsen** [comment]
The special case for Python 3.7 is no longer necessary. I will remove that and merge.

**Pull request merged**
